import { NextResponse } from "next/server";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const period = searchParams.get("period") || "30d";

  // In production, this would query the database via Prisma
  const data = {
    metrics: [
      {
        label: "Faturamento Hoje",
        value: "R$ 12.450,00",
        change: 15.3,
        icon: "DollarSign",
        color: "text-orange-400",
        bgColor: "bg-orange-500/10",
      },
      {
        label: "Faturamento Mês",
        value: "R$ 287.500,00",
        change: 22.1,
        icon: "BarChart3",
        color: "text-green-400",
        bgColor: "bg-green-500/10",
      },
      {
        label: "Lucro Líquido",
        value: "R$ 186.875,00",
        change: 18.7,
        icon: "TrendingUp",
        color: "text-emerald-400",
        bgColor: "bg-emerald-500/10",
      },
      {
        label: "Vendas",
        value: "342",
        change: 12.5,
        icon: "ShoppingCart",
        color: "text-blue-400",
        bgColor: "bg-blue-500/10",
      },
      {
        label: "Ticket Médio",
        value: "R$ 840,35",
        change: 8.2,
        icon: "Target",
        color: "text-purple-400",
        bgColor: "bg-purple-500/10",
      },
      {
        label: "Leads",
        value: "1.247",
        change: 25.6,
        icon: "UserPlus",
        color: "text-cyan-400",
        bgColor: "bg-cyan-500/10",
      },
      {
        label: "Conversão",
        value: "4.8%",
        change: 1.3,
        icon: "Zap",
        color: "text-amber-400",
        bgColor: "bg-amber-500/10",
      },
      {
        label: "Investimento Tráfego",
        value: "R$ 45.200,00",
        change: -5.2,
        icon: "Megaphone",
        color: "text-pink-400",
        bgColor: "bg-pink-500/10",
      },
      {
        label: "ROAS",
        value: "6.3x",
        change: 15.8,
        icon: "RotateCcw",
        color: "text-teal-400",
        bgColor: "bg-teal-500/10",
      },
      {
        label: "Clientes Ativos",
        value: "892",
        change: 9.4,
        icon: "Users",
        color: "text-indigo-400",
        bgColor: "bg-indigo-500/10",
      },
    ],
    faturamentoChart: [
      { name: "01", value: 8200 },
      { name: "03", value: 9100 },
      { name: "05", value: 7800 },
      { name: "07", value: 12400 },
      { name: "09", value: 11200 },
      { name: "11", value: 15600 },
      { name: "13", value: 13800 },
      { name: "15", value: 16200 },
      { name: "17", value: 14500 },
      { name: "19", value: 18900 },
      { name: "21", value: 17300 },
      { name: "23", value: 21400 },
      { name: "25", value: 19800 },
      { name: "27", value: 23100 },
      { name: "29", value: 22450 },
      { name: "30", value: 12450 },
    ],
    vendasChart: [
      { name: "01", vendas: 24, meta: 30 },
      { name: "05", vendas: 28, meta: 30 },
      { name: "09", vendas: 35, meta: 32 },
      { name: "13", vendas: 31, meta: 32 },
      { name: "17", vendas: 42, meta: 35 },
      { name: "21", vendas: 38, meta: 35 },
      { name: "25", vendas: 45, meta: 40 },
      { name: "29", vendas: 41, meta: 40 },
      { name: "30", vendas: 58, meta: 45 },
    ],
    lucroChart: [
      { name: "01", receita: 8200, custo: 3200 },
      { name: "05", receita: 7800, custo: 3100 },
      { name: "09", receita: 11200, custo: 4200 },
      { name: "13", receita: 13800, custo: 5100 },
      { name: "17", receita: 14500, custo: 5400 },
      { name: "21", receita: 17300, custo: 6200 },
      { name: "25", receita: 19800, custo: 7100 },
      { name: "29", receita: 23100, custo: 8400 },
      { name: "30", receita: 12450, custo: 4800 },
    ],
    origemVendas: [
      { name: "Orgânico", value: 35, color: "#f97316" },
      { name: "Facebook Ads", value: 25, color: "#3b82f6" },
      { name: "Google Ads", value: 18, color: "#a855f7" },
      { name: "Indicação", value: 12, color: "#22c55e" },
      { name: "Email", value: 6, color: "#ec4899" },
      { name: "Outros", value: 4, color: "#06b6d4" },
    ],
    produtosTop: [
      { name: "Plano Anual", vendas: 89 },
      { name: "Mentoria VIP", vendas: 67 },
      { name: "E-book Pack", vendas: 54 },
      { name: "Plano Mensal", vendas: 48 },
      { name: "Curso Completo", vendas: 42 },
      { name: "Consultoria", vendas: 31 },
    ],
    campanhasRoas: [
      { name: "Black Friday", roas: 8.2 },
      { name: "Lançamento", roas: 6.5 },
      { name: "Retargeting", roas: 5.8 },
      { name: "Awareness", roas: 3.2 },
      { name: "Reengajamento", roas: 4.1 },
      { name: "Afiliados", roas: 7.3 },
    ],
    funnel: [
      { stage: "Visitantes", count: 45200, color: "#f97316" },
      { stage: "Leads", count: 12470, color: "#fb923c" },
      { stage: "Checkout", count: 3840, color: "#fbbf24" },
      { stage: "Pagamento", count: 2150, color: "#22c55e" },
      { stage: "Venda", count: 1890, color: "#06b6d4" },
      { stage: "Cliente Recorrente", count: 892, color: "#a855f7" },
    ],
    attention: [
      {
        id: "1",
        icon: "DollarSign",
        title: "Pagamentos Pendentes",
        description:
          "3 transações aguardando confirmação do pagamento totalizando R$ 2.450,00",
        count: 3,
        severity: "warning",
        action: "Verificar pagamentos",
      },
      {
        id: "2",
        icon: "TrendingDown",
        title: "Queda em Campanhas",
        description:
          "2 campanhas com ROAS abaixo de 2.0 nos últimos 7 dias",
        count: 2,
        severity: "danger",
        action: "Revisar campanhas",
      },
      {
        id: "3",
        icon: "Package",
        title: "Produtos com Estoque Baixo",
        description:
          "3 produtos digitais com baixa disponibilidade ou sem licença ativa",
        count: 3,
        severity: "warning",
        action: "Atualizar estoque",
      },
      {
        id: "4",
        icon: "UserPlus",
        title: "Leads sem Conversão",
        description:
          "156 leads qualificados sem interação nos últimos 14 dias",
        count: 156,
        severity: "info",
        action: "Iniciar sequência",
      },
      {
        id: "5",
        icon: "CreditCard",
        title: "Assinaturas para Expirar",
        description:
          "28 assinaturas vencendo nos próximos 7 dias - potencial de churn",
        count: 28,
        severity: "warning",
        action: "Campanha de retenção",
      },
      {
        id: "6",
        icon: "Clock",
        title: "Tarefas Atrasadas",
        description:
          "7 tarefas de conteúdo e revisão atrasadas no pipeline",
        count: 7,
        severity: "danger",
        action: "Ver tarefas pendentes",
      },
    ],
  };

  return NextResponse.json(data);
}
